[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_project = "GXSHqMQ9t85xXt2F7HBFC4h2r5qdg7NezrXb6GxwQk9p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/escrow_project-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
